# Generated by Django 2.1.2 on 2018-10-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neco', '0002_auto_20181018_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Title', max_length=20),
        ),
    ]
